apiVersion: namespaceclass.akuity.io/v1alpha1
kind: NamespaceClass
metadata:
  name: public-network
spec:
  resources:
    - apiVersion: networking.k8s.io/v1
      kind: NetworkPolicy
      metadata:
        name: allow-all
      spec:
        podSelector: {}
        ingress:
          - {}
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: public-config
      data:
        network: public